nevladinaOrg.Web/Areas/Administration/ViewModels/ContactTypeViewModel.cs
using Core.Entities.Base;
using nevladinaOrg.Web.Helpers;
using System.ComponentModel.DataAnnotations;

namespace nevladinaOrg.Web.Areas.Administration.ViewModels
{
    public class ContactTypeViewModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = nameof(Localizer.ErrorMessageNameReq)),
         StringLength(100, ErrorMessage = nameof(Localizer.ErrorMessageNameLen100))]
        public string Name { get; set; }



        public static implicit operator ContactType(ContactTypeViewModel model)
        {
            ContactType contactType = new ContactType()
            {
                Id = model.Id,
                Name = model.Name
            };

            return contactType;
        }

        public static implicit operator ContactTypeViewModel(ContactType model)
        {
            ContactTypeViewModel contactTypeViewModel = new ContactTypeViewModel()
            {
                Id = model.Id,
                Name = model.Name
            };

            return contactTypeViewModel;
        }
    }
}

nevladinaOrg.Web/Areas/Administration/Controllers/ContactTypesController.cs
using Core.Constants;
using Core.Entities.Base;
using DAL;
using nevladinaOrg.Web.Areas.Administration.ViewModels;
using nevladinaOrg.Web.Constants;
using nevladinaOrg.Web.Controllers;
using nevladinaOrg.Web.Helpers;
using nevladinaOrg.Web.Helpers.Breadcrumb;
using nevladinaOrg.Web.Helpers.Logger;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace nevladinaOrg.Web.Areas.Administration.Controllers
{
    [Area(MagicStrings.AreaNames.Administration)]
    [Authorization]
    public class ContactTypesController : BaseController
    {
        #region Properties
        private readonly IDataUnitOfWork _datUnitOfWork;

        private readonly ILogger _logger;
        #endregion

        public ContactTypesController(
            IDataUnitOfWork datUnitOfWork,
            IBreadcrumb breadcrumb,
            IStringLocalizerFactory stringLocalizerFactory,
            ILogger logger)
            : base(breadcrumb, stringLocalizerFactory)
        {
            _datUnitOfWork = datUnitOfWork;

            _logger = logger;
        }

        #region Index
        public JsonResult JsonIndex()
        {
            IEnumerable<ContactType> contactTypes = _datUnitOfWork.BaseUow.ContactTypesRepository.GetAll();

            var contactTypesJson = JsonConvert.SerializeObject(contactTypes);

            return new JsonResult(contactTypesJson);
        }
        #endregion

        #region Add
        [HttpGet]
        public IActionResult Add()
        {
            return PartialView(MagicStrings.ViewNames._Add, new ContactTypeViewModel());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Add(ContactTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return PartialView(MagicStrings.ViewNames._Add, model);

            if (_datUnitOfWork.BaseUow.ContactTypesRepository.GetExists(model.Name))
                ModelState.AddModelError(nameof(Localizer.RecordAlreadyExists), Localizer.RecordAlreadyExists);

            if (ModelState.IsValid)
            {
                try
                {
                    _datUnitOfWork.BaseUow.ContactTypesRepository.Add(model);
                    _datUnitOfWork.BaseUow.ContactTypesRepository.SaveChanges();

                    _logger.Log(Enumerations.LogTypes.Info, Enumerations.LogActivity.Add, Tables.Base.ContactTypes, model.Id, GetControllerName(), GetActionName(), null);

                    return Json(new { success = true, notification = new Notification(NotificationTypes.Success, Localizer.Saved, string.Format(Localizer.SuccessfullySavedAndRecordName, model.Name)).ConvertToJson() });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(Localizer.Error), Localizer.Error);

                    _logger.Log(Enumerations.LogTypes.Error, Enumerations.LogActivity.Add, Tables.Base.ContactTypes, model.Id, GetControllerName(), GetActionName(), ex);
                }
            }

            return PartialView(MagicStrings.ViewNames._Add, model);
        }
        #endregion

        #region Edit
        [HttpGet]
        public IActionResult Edit(int ContactTypeId)
        {
            ContactTypeViewModel contactTypeViewModel = _datUnitOfWork.BaseUow.ContactTypesRepository.GetById(ContactTypeId);
            return PartialView(MagicStrings.ViewNames._Edit, contactTypeViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(ContactTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return PartialView(MagicStrings.ViewNames._Edit, model);

            try
            {
                _datUnitOfWork.BaseUow.ContactTypesRepository.Update(model);
                _datUnitOfWork.BaseUow.ContactTypesRepository.SaveChanges();

                _logger.Log(Enumerations.LogTypes.Info, Enumerations.LogActivity.Edit, Tables.Base.ContactTypes, model.Id, GetControllerName(), GetActionName(), null);

                return Json(new { success = true, notification = new Notification(NotificationTypes.Success, Localizer.Saved, string.Format(Localizer.SuccessfullySavedAndRecordName, model.Name)).ConvertToJson() });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(nameof(Localizer.Error), Localizer.Error);

                _logger.Log(Enumerations.LogTypes.Error, Enumerations.LogActivity.Edit, Tables.Base.ContactTypes, model.Id, GetControllerName(), GetActionName(), ex);
            }

            return PartialView(MagicStrings.ViewNames._Edit, model);
        }
        #endregion

        #region Delete
        public JsonResult Delete(int Id)
        {
            ContactType contactType = _datUnitOfWork.BaseUow.ContactTypesRepository.GetById(Id);
            Notification notification = null;
            try
            {
                if (contactType != null)
                {
                    _datUnitOfWork.BaseUow.ContactTypesRepository.Remove(contactType);
                    _datUnitOfWork.BaseUow.ContactTypesRepository.SaveChanges();

                    _logger.Log(Enumerations.LogTypes.Info, Enumerations.LogActivity.Delete, Tables.Base.ContactTypes, Id, GetControllerName(), GetActionName(), null);
                    notification = new Notification(NotificationTypes.Success, Localizer.Removed, string.Format(Localizer.SuccessfullyRemovedName, contactType.Name));
                }
            }
            catch (Exception ex)
            {
                notification = new Notification(NotificationTypes.Error, Localizer.Error, Localizer.AnErrorOccurredFriendly);
                _logger.Log(Enumerations.LogTypes.Error, Enumerations.LogActivity.Delete, Tables.Base.ContactTypes, Id, GetControllerName(), GetActionName(), ex);
            }

            return Json(notification.ConvertToJson());
        }

        public JsonResult DeleteAll(List<int> list)
        {
            List<ContactType> modelList = new List<ContactType>();
            Notification notification = null;
            try
            {
                foreach (var item in list)
                {
                    modelList.Add(_datUnitOfWork.BaseUow.ContactTypesRepository.GetById(item));
                }
                _datUnitOfWork.BaseUow.ContactTypesRepository.RemoveRange(modelList);
                _datUnitOfWork.BaseUow.ContactTypesRepository.SaveChanges();
                foreach (var item in modelList)
                {
                    _logger.Log(Enumerations.LogTypes.Info, Enumerations.LogActivity.Delete, Tables.Base.ContactTypes, item.Id, GetControllerName(), GetActionName(), null);
                }
                notification = new Notification(NotificationTypes.Success, Localizer.Removed, string.Format(Localizer.SuccessfullyRemovedName, Localizer.ContactTypes));
            }
            catch (Exception ex)
            {
                notification = new Notification(NotificationTypes.Error, Localizer.ErrorFriendly, Localizer.AnErrorOccurredFriendly);
                foreach (var item in list)
                {
                    _logger.Log(Enumerations.LogTypes.Error, Enumerations.LogActivity.Delete, Tables.Base.ContactTypes, item, GetControllerName(), GetActionName(), ex);
                }
            }
            return Json(notification.ConvertToJson());
        }
        #endregion
    }
}

nevladinaOrg.Web/Areas/Administration/Views/ContactTypes/_Add.cshtml
@model ContactTypeViewModel

@inject Localizer Localizer
@inject ISelectListHelper SelectList

@{
    Layout = "~/Views/Shared/_ModalLayout.cshtml";
}

<div class="modal-header">
    <h5 class="modal-title">@Localizer.AddContactTypes</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<form asp-antiforgery="true" data-ajax-url="@Url.Action("Add", "ContactTypes", new { area = "Administration" })" data-ajax="true" data-ajax-method="post" data-ajax-success="hideModal" data-ajax-update="#update-modal">
    <div class="modal-body">

        @if (!ViewData.ModelState.IsValid)
        {
            <div class="m-alert m-alert--icon m-alert--outline alert alert-danger alert-dismissible animated fadeIn" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-warning"></i>
                </div>
                <div class="m-alert__text">
                    @Html.ValidationSummary()
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        }

        <div class="form-group m-form__group row">
            <div class="col-lg-12">
                <label class="form-control-label">* @Localizer.Name</label>
                <input type="text" asp-for="Name" class="form-control m-input" placeholder="@Localizer.Name">
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="modal-footer">
        <div class="form-actions right">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer.Close</button>
            <button type="submit" class="btn btn-primary">@Localizer.Save</button>
        </div>
    </div>
</form>

@section scripts {
    <script type="text/javascript">
        function hideModal(data) {
            if (data.success) {
                $("#m_contactTypes_index__datatable").mDatatable().destroy();
                ContactTypes();
                closeModal();

                $("#m_js__notification").text(data.notification.value);
                NotificationHandler(data.notification.value);
            }
        }
    </script>
}

nevladinaOrg.Web/Areas/Administration/Views/ContactTypes/_Edit.cshtml
@model ContactTypeViewModel

@inject Localizer Localizer
@inject ISelectListHelper SelectList

@{
    Layout = "~/Views/Shared/_ModalLayout.cshtml";
}



<div class="modal-header">
    <h5 class="modal-title">@Localizer.EditContactType</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<form asp-antiforgery="true" data-ajax-url="@Url.Action("Edit", "ContactTypes", new { area = "Administration" })" data-ajax="true" data-ajax-method="post" data-ajax-success="hideModal" data-ajax-update="#update-modal">
    <div class="modal-body">
        <input hidden asp-for="Id" />

        @if (!ViewData.ModelState.IsValid)
        {
            <div class="m-alert m-alert--icon m-alert--outline alert alert-danger alert-dismissible animated fadeIn" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-warning"></i>
                </div>
                <div class="m-alert__text">
                    @Html.ValidationSummary()
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        }
        <div class="form-group m-form__group row">
            <div class="col-lg-12">
                <label class="form-control-label">* @Localizer.Name</label>
                <input type="text" asp-for="Name" class="form-control m-input" placeholder="@Localizer.Name">
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="modal-footer">
        <div class="form-actions right">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer.Close</button>
            <button type="submit" class="btn btn-primary">@Localizer.Edit</button>
        </div>
    </div>
</form>

@section scripts {
    <script type="text/javascript">

        function hideModal(data) {
            if (data.success) {
                $("#m_contactTypes_index__datatable").mDatatable().destroy();
                ContactTypes();
                closeModal();

                $("#m_js__notification").text(data.notification.value);
                NotificationHandler(data.notification.value);
            }
        }
    </script>
}

nevladinaOrg.Web/Areas/Administration/Views/ContactTypes/_Index.cshtml
@inject Localizer Localizer
@inject ISelectListHelper SelectList

@{
    Layout = null;
}

<div class="m-portlet m-portlet--responsive-mobile">
    <div class="m-portlet__head" style="">
        <div class="m-portlet__head-progress">
            <!-- here can place a progress bar-->
        </div>
        <div class="m-portlet__head-wrapper">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon">
                        <i class="flaticon-placeholder-1"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        @Localizer.ContactTypes
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                    <a href="@Url.Action("Add", "ContactTypes", new { area = "Administration" })" class="btn btn-brand m-btn--icon m-btn--wide modal-link">
                        <span>
                            <i class="la la-plus"></i>
                            <span>@Localizer.ContactType</span>
                        </span>
                    </a>
            </div>
        </div>
    </div>
    <div class="m-portlet__body">
        <!--begin: Search Form -->
        <div class="m-form m-form--label-align-right m--margin-top-10 m--margin-bottom-30">
            <div class="row align-items-center">
                <div class="col-xl-8"></div>
                <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                    <div class="m-input-icon m-input-icon--left">
                        <input type="text" class="form-control m-icon" placeholder="@Localizer.SearchDots" id="m_contactTypes_index__generalSearch">
                        <span class="m-input-icon__icon m-input-icon__icon--left">
                            <span>
                                <i class="la la-search"></i>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <!--end: Search Form -->
        <!--begin: Selected Rows Group Action Form -->
        <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30 collapse" id="m_datatable_group_action_contactTypes" style="">
            <div class="row align-items-center">
                <div class="col-xl-12">
                    <div class="m-form__group m-form__group--inline">
                        <div class="m-form__label m-form__label-no-wrap">
                            <label class="m--font-bold m--font-danger-">
                                @Localizer.Selected
                                <span id="m_datatable_selected_number_contactTypes"></span> @Localizer.records:
                            </label>
                        </div>
                        <div class="m-form__control">
                            <div class="btn-toolbar">
                                &nbsp;&nbsp;&nbsp;
                                <button class="btn btn-sm btn-danger" type="button" id="m_datatable_delete_all_contactTypes">@Localizer.DeleteAll</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end: Selected Rows Group Action Form -->
        <!--begin: Datatable -->
        <div class="m_datatable" id="m_contactTypes_index__datatable"></div>
        <!--end: Datatable -->
    </div>
</div>

<script>

    function ContactTypes () {
        const jedan = true; // varijable za metronic datatable true i false umjesto 1 i 0
        const nula = false;
        var DatatableDataLocal, DatatableDatasource, DatatableOptions;
        $.ajax({
            url: "@Url.Action("JsonIndex", "ContactTypes", new { area = "Administration" })",
            type: "GET",
            success: function (data) {
                DatatableDatasource = JSON.parse(data);
                var DatatableDataLocal = function () {
                    var DatatableOptions = {
                        data: {
                            type: "local",
                            source: DatatableDatasource,
                            pageSize: 10
                        },
                        layout: {
                            theme: "default",
                            class: "",
                            scroll: !nula,
                            height: 550,
                            footer: !jedan
                        },
                        pagination: !nula,
                        columns: [{
                            field: "@nameof(Core.Entities.Base.ContactType.Id)",
                            title: "#",
                            sortable: !jedan,
                            width: 35,
                            textAlign: "center",
                            selector: {
                                class: "m-checkbox--solid m-checkbox--brand"
                            }
                        }, {
                            field: "@nameof(Core.Entities.Base.ContactType.Name)",
                            title: "@Localizer.ContactType",
                            filterable: !nula,
                            sortable: !nula,
                        },{
                            field: "@string.Empty",
                                title: "@string.Empty",
                                sortable: !jedan,
                            filterable: !jedan
                        }, {
                            field: "Actions",
                            title: "@Localizer.Action",
                            textAlign: "center",
                            width: 70,
                            sortable: !jedan,
                            overflow: "visible",
                            template: function (DatatableDatasource, a) {
                                return '<a href="@Url.Action("Edit", "ContactTypes", new { area = "Administration" })?ContactTypeId=' + DatatableDatasource.Id + '"class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill modal-link" title="@Localizer.Edit">\t\t\t\t\t\t\t<i class="la la-edit"></i>\t\t\t\t\t\t</a>\t\t\t\t\t\t<a data-id="' + DatatableDatasource.Id + '" data-behavior="delete" href="@Url.Action("Delete", "ContactTypes", new { area = "Administration" })/' + DatatableDatasource.Id + '" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" data-ajax-success="hideModal" title="@Localizer.Delete">\t\t\t\t\t\t\t<i class="la la-trash"></i>\t\t\t\t\t\t</a>'
                            }
                        }],
                        translate: {
                            records: {
                                processing: '@Localizer.LoadingDots',
                                noRecords: '@Localizer.NoRecordsFound'
                            },
                            toolbar: {
                                pagination: {
                                    items: {
                                        default: {
                                            first: '@Localizer.First',
                                            prev: '@Localizer.Previous',
                                            next: '@Localizer.Next',
                                            last: '@Localizer.Last',
                                            more: '@Localizer.MorePages',
                                            input: '@Localizer.PageNumber',
                                            select: '@Localizer.SelectPageSize'
                                        },
                                        info: '@Localizer.DisplayingNumberOfRecords'
                                    }
                                }
                            }
                        }
                    };
                    return {
                        init: function () {
                            ! function () {
                                DatatableOptions.search = {
                                    input: $("#m_contactTypes_index__generalSearch")
                                };
                                var e = $("#m_contactTypes_index__datatable").mDatatable(DatatableOptions);
                                e.on("m-datatable--on-check m-datatable--on-uncheck m-datatable--on-layout-updated", function (t) {
                                    var a = e.rows(".m-datatable__row--active").nodes().length;
                                    $("#m_datatable_selected_number_contactTypes").html(a), a > 0 ? $("#m_datatable_group_action_contactTypes").collapse("show") : $("#m_datatable_group_action_contactTypes").collapse("hide");
                                    a = 0;
                                })
                                $("#m_datatable_delete_all_contactTypes").on('click', function () {
                                    var list = [];
                                    for (var i = 0; i < e.rows(".m-datatable__row--active").nodes().length; i++) {
                                        list.push((parseInt($(e.rows(".m-datatable__row--active").nodes()[i]).find("input[type=checkbox]").val())));
                                    }
                                    $.ajax({
                                        url: "@Url.Action("DeleteAll", "ContactTypes", new { area = "Administration" })",
                                        type: "GET",
                                        data: { list: list },
                                        traditional:true,
                                        success: function (data) {
                                            NotificationHandler(data.value);
                                            e.rows(".m-datatable__row--active").nodes().html("");
                                            $("#m_datatable_group_action_contactTypes").collapse("hide");
                                        }
                                    })
                                })
                            }()
                        }
                    }
                }();
                jQuery(document).ready(function () {
                    DatatableDataLocal.init()
                });
            }
        });
    };
    ContactTypes();
</script>