nevladinaOrg.Web/Areas/Institutions/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Core.Constants;
using Core.Entities.Base;
using Core.Entities.Base.DTO;
using DAL;
using DAL.Repositories.Base.IRepository;
using DAL.Repositories.Base.IRepository.DTO;
using nevladinaOrg.Web.Areas.Institutions.ViewModels;
using nevladinaOrg.Web.Areas.Organizations.ViewModels;
using nevladinaOrg.Web.Constants;
using nevladinaOrg.Web.Controllers;
using nevladinaOrg.Web.Helpers;
using nevladinaOrg.Web.Helpers.Breadcrumb;
using nevladinaOrg.Web.Helpers.ImageHelper;
using nevladinaOrg.Web.Helpers.Logger;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using Authorization = nevladinaOrg.Web.Helpers.Authorization;

namespace nevladinaOrg.Web.Areas.Institutions.Controllers
{
    [Area(MagicStrings.AreaNames.Institutions)]
    [WebRoles(Enumerations.WebRoles.InstitutionAdministrator)]
    public class StaffController : BaseController
    {
        #region Properties
        IDataUnitOfWork _dataUnitOfWork;

        private Localizer _localizer;
        private ILogger _logger;
        private IImageHelper _imageHelper;
        #endregion

        public StaffController(IDataUnitOfWork dataUnitOfWork,
            Localizer localizer, ILogger logger, IImageHelper imageHelper,
            IBreadcrumb breadcrumb, IStringLocalizerFactory stringLocalizerFactory)
                    : base(breadcrumb, stringLocalizerFactory)
        {
            _dataUnitOfWork = dataUnitOfWork;

            _localizer = localizer;
            _logger = logger;
            _imageHelper = imageHelper;
        }


        #region Index

        public IActionResult Index()
        {
            return View();
        }
        public JsonResult JsonIndexLicense(int MemberId)
        {
            var licenseDTO = _dataUnitOfWork.BaseUow.LicenseDTORepository.GetByMemberId(MemberId).ToList();
            var licenseDTOJson = JsonConvert.SerializeObject(licenseDTO);
            return new JsonResult(licenseDTOJson);
        }
        public JsonResult JsonIndex()
        {
            //IEnumerable<OrganizationInstitutionUserDTO> organizationInstitutionUsersDTO = null;
            //List<PersonDTO> personsDTO = null;
            //if (LoggedUserIds.OrganizationId.HasValue)
            //{
            //    organizationInstitutionUsersDTO = _dataUnitOfWork.BaseUow.OrganizationInstitutionUsersRepositoryDTORepository.GetAllByOrganizationId(LoggedUserIds.OrganizationId.Value).ToList();   //LoggedUser.organizationID 
            //}
            //if (organizationInstitutionUsersDTO != null)
            //{
            //    //var users = _dataUnitOfWork.BaseUow.PersonsRepository.GetByUserIds(organizationInstitutionUsersDTO.Select(x => x.UserId).ToList());
            //    //foreach (var institutionUser in organizationInstitutionUsersDTO)
            //    //{
            //    //    institutionUser.User = users.FirstOrDefault(x => x.Id == institutionUser.UserId).FirstName + " " + users.FirstOrDefault(x => x.Id == institutionUser.UserId).LastName;
            //    //}
            //    //OrganizationInstitutionUserId,InstiuttionUserId,UserId
            //    List<Tuple<int, int, int>> organizationInstitutionUsersIds = organizationInstitutionUsersDTO.Select(x => new Tuple<int, int, int>(x.Id, x.InstitutionUserId, x.UserId)).ToList();
            //    personsDTO = _personsDTORepository.GetByUserIds(organizationInstitutionUsersIds.Select(x => x.Item3).ToList()).ToList();
            //    foreach (var person in personsDTO)
            //    {
            //        person.OrganizationInstitutionUserId = organizationInstitutionUsersIds.FirstOrDefault(x => x.Item3 == person.Id).Item1;
            //        person.InstitutionUserId  = organizationInstitutionUsersIds.FirstOrDefault(x => x.Item3 == person.Id).Item2;
            //    }

            //}
            //var personsDTOJson = JsonConvert.SerializeObject(personsDTO);
            //return new JsonResult(personsDTOJson);

            var institutionUsersDTO = _dataUnitOfWork.BaseUow.InstitutionUsersDTORepository.GetByInstitutionId(LoggedUserIds.InstitutionId).ToList();


            List<Tuple<int, int, int>> institutionUsersIds = institutionUsersDTO.Select(x => new Tuple<int, int, int>(x.Id, x.InstitutionId, x.UserId)).ToList();
            var personsDTO = _dataUnitOfWork.BaseUow.PersonsDTORepository.GetByUserIds(institutionUsersIds.Select(x => x.Item3).ToList()).ToList();
            foreach (var person in personsDTO)
            {
                person.InstitutionUserId = institutionUsersIds.FirstOrDefault(x => x.Item3 == person.Id).Item1;
                person.InstitutionId = institutionUsersIds.FirstOrDefault(x => x.Item3 == person.Id).Item2;
            }

            var institutionUsersDTOJson = JsonConvert.SerializeObject(personsDTO);
            return new JsonResult(institutionUsersDTOJson);
        }

        public JsonResult JsonIndexEvents(int PersonId)
        {
            IEnumerable<EventDTO> events = _dataUnitOfWork.BaseUow.EventsDTORepository.GetByUserId(PersonId);

            var eventsJson = JsonConvert.SerializeObject(events);

            return new JsonResult(eventsJson);
        }
        #endregion

        #region Add

        public IActionResult Add()
        {
            var model = new StaffViewModel()
            {
                GeneralInfo = new StaffGeneralInfoViewModel
                {
                    Person = new PersonViewModel(),
                    PersonMobile = new PersonContact() { ContactTypeId = (int)Enumerations.ContactTypes.MobileNumber },
                    PersonPhone = new PersonContact() { ContactTypeId = (int)Enumerations.ContactTypes.PhoneNumber },
                    PersonPrimaryEmail = new PersonContact() { ContactTypeId = (int)Enumerations.ContactTypes.PrimaryEmail },
                    PersonSecondaryEmail = new PersonContact() { ContactTypeId = (int)Enumerations.ContactTypes.SecondaryEmail }
                },
                StatusInfo = new StaffStatusInfoViewModel
                {
                    PersonDetail = new PersonDetailsViewModel()
                },
                AccountInfo = new StaffAccountInfoViewModel
                {
                    Roles = new List<string>(),
                    User = new UserViewModel()
                }
            };
            return PartialView(MagicStrings.ViewNames._Add, model);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Add(StaffViewModel model)
        {
            if (model.GeneralInfo.PersonPhone.Contact == null)
            {
                ModelState.AddModelError(nameof(Localizer.ErrorMessageContactPhoneReq), Localizer.ErrorMessageContactPhoneReq);
            }
            if (model.GeneralInfo.PersonPrimaryEmail.Contact == null)
            {
                ModelState.AddModelError(nameof(Localizer.ErrorMessagePrimaryEmailReq), Localizer.ErrorMessagePrimaryEmailReq);
            }
            var pattern = new Regex("(?=.*[0-9])(?=.*[a-zA-Z]).");
            if (!pattern.IsMatch(model.AccountInfo.User.Password))
            {
                ModelState.AddModelError(nameof(Localizer.ErrorMessagePasswordReqContainLettersAndNumbers), Localizer.ErrorMessagePasswordReqContainLettersAndNumbers);
            }
            if (model.AccountInfo.User.Password.Count() < 6)
            {
                ModelState.AddModelError(nameof(Localizer.ErrorMessagePasswordLen6), Localizer.ErrorMessagePasswordLen6);
            }

            if (model.CurrentStep == 3 && ModelState.IsValid)
            {
                model.CurrentStep = 4;
                return PartialView(MagicStrings.ViewNames._Add, model);
            }
            if (ModelState.IsValid)
            {

                using (IDbContextTransaction contextTransaction = _dataUnitOfWork.BaseUow.InstitutionUsersRepository.BeginTransaction())
                {
                    model.GeneralInfo.Person.CitizenshipId = model.GeneralInfo.Person.CitizenshipId == 0 ? null : model.GeneralInfo.Person.CitizenshipId;
                    model.GeneralInfo.Person.BirthCityId = model.GeneralInfo.Person.BirthCityId == 0 ? null : model.GeneralInfo.Person.BirthCityId;
                    model.GeneralInfo.Person.RegionId = model.GeneralInfo.Person.RegionId == 0 ? null : model.GeneralInfo.Person.RegionId;
                    model.GeneralInfo.Person.BirthCountryId = model.GeneralInfo.Person.BirthCountryId == 0 ? null : model.GeneralInfo.Person.BirthCountryId;
                    model.GeneralInfo.Person.ResidenceId = model.GeneralInfo.Person.ResidenceId == 0 ? null : model.GeneralInfo.Person.ResidenceId;
                    model.StatusInfo.PersonDetail.MartialStatusId = model.StatusInfo.PersonDetail.MartialStatusId == 0 ? null : model.StatusInfo.PersonDetail.MartialStatusId;
                    model.StatusInfo.PersonDetail.AcademicTitleId = model.StatusInfo.PersonDetail.AcademicTitleId == 0 ? null : model.StatusInfo.PersonDetail.AcademicTitleId;
                    model.StatusInfo.PersonDetail.EmploymentStatusId = model.StatusInfo.PersonDetail.EmploymentStatusId == 0 ? null : model.StatusInfo.PersonDetail.EmploymentStatusId;

                    var user = new User();
                    user = model.AccountInfo.User;

                    var person = new Person();
                    person = model.GeneralInfo.Person;

                    var personDetails = new PersonDetail();
                    personDetails = model.StatusInfo.PersonDetail;


                    try
                    {
                        //
                        _dataUnitOfWork.BaseUow.PersonsRepository.Add(person);
                        _dataUnitOfWork.BaseUow.PersonsRepository.SaveChanges();

nevladinaOrg.Web/Controllers/AccessController.cs
using Core.Entities.Base;
using DAL;
using DAL.Repositories.Base.IRepository;
using nevladinaOrg.Web.Helpers;
using nevladinaOrg.Web.Helpers.Breadcrumb;
using nevladinaOrg.Web.Helpers.Culture;
using nevladinaOrg.Web.ViewModels;
using nevladinaOrg.Web.ViewModels.Access;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;

namespace nevladinaOrg.Web.Controllers
{
    public class AccessController : BaseController
    {
        private readonly IDataUnitOfWork _dataUnitOfWork;

        private readonly ICulture _culture;

        public AccessController(IDataUnitOfWork dataUnitOfWork,
                                ICulture culture,
                                IBreadcrumb breadcrumb,
                                IStringLocalizerFactory stringLocalizerFactory) : base(breadcrumb, stringLocalizerFactory)
        {
            _dataUnitOfWork = dataUnitOfWork;
            _culture = culture;
        }

        #region Login

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = _dataUnitOfWork.BaseUow.UsersRepository.GetByUsername(model.Username);
            if (user == null || !Cryptography.Hash.Validate(model.Password, user.PasswordSalt, user.PasswordHash))
            {
                ModelState.AddModelError(string.Empty, Localizer.IncorrectUsernameOrPassword);
                return View(model);
            }
            var baseUser = _dataUnitOfWork.BaseUow.UsersRepository.GetById(user.Id);
            

            var userAccounts = _dataUnitOfWork.BaseUow.UsersDTORepository.GetByUserId(user.Id).ToList();
            var userAccount = userAccounts.FirstOrDefault();
            var personUser = _dataUnitOfWork.BaseUow.PersonUsersDTORepository.GetById(userAccount.UserId);

            /* POTREBNO DOVRŠITI - RAZDVOJI U DVIJE AKCIJE */

            //if (userAccounts.Count > 1)
            //{
            //    int[] institutionIds = userAccounts.Where(x => !x.OrganizationId.HasValue).GroupBy(x => x.InstitutionId).Select(x => x.Key).ToArray();
            //    int?[] organizationIds = userAccounts.Where(x => x.OrganizationId.HasValue).GroupBy(x => x.OrganizationId).Select(x => x.Key).ToArray();

            //    if (institutionIds.Length + (organizationIds?.Length ?? 0) != 1)
            //    {
            //        model.Institutions = institutionIds.Length != 0 ? _dataUnitOfWork.AuthUow.InstitutionsAuthRepository.GetByInstitutionIds(institutionIds) : null;
            //        model.Organizations = (organizationIds?.Length ?? 0) != 0 ? _dataUnitOfWork.AuthUow.OrganizationsAuthRepository.GetByOrganizationIds(organizationIds) : null;
            //    }
            //}

            IEnumerable<Functionality> functionalities = null;
            if (userAccount.OrganizationInstitutionUserId.HasValue)
                functionalities = _dataUnitOfWork.BaseUow.FunctionalitiesRepository.GetByOrganizationInstitutionUserId(userAccount.OrganizationInstitutionUserId.Value);
            else
                functionalities = _dataUnitOfWork.BaseUow.FunctionalitiesRepository.GetByInstitutionUserId(userAccount.InstitutionUserId);


            IEnumerable<Role> roles = null;
            if (userAccount.OrganizationInstitutionUserId.HasValue)
                roles = _dataUnitOfWork.BaseUow.RolesRepository.GetByOrganizationInstitutionUserId(userAccount.OrganizationInstitutionUserId.Value);
            else
                roles = _dataUnitOfWork.BaseUow.RolesRepository.GetByInstitutionUserId(userAccount.InstitutionUserId);

            var loggedUserViewModel = new LoggedUserDataViewModel
            {
                User = userAccount,
                PersonUser = personUser,
                Functionalities = functionalities,
                Roles=roles
            };

            if (loggedUserViewModel.User.OrganizationInstitutionUserId.HasValue)
               _dataUnitOfWork.BaseUow.OrganizationInstitutionUsersRepository.SetLastLogin(loggedUserViewModel.User.OrganizationInstitutionUserId.Value, DateTime.Now);
            else
                _dataUnitOfWork.BaseUow.InstitutionUsersRepository.SetLastLogin(loggedUserViewModel.User.InstitutionUserId, DateTime.Now);

            HttpContext.SetLoggedUser(loggedUserViewModel, model.RememberMe);

            _culture.Set(user.CultureName);

            //if (!string.IsNullOrWhiteSpace(model.RedirectTo))
                //return Redirect(model.RedirectTo);

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Logout

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.SetLoggedUser(null);

            return RedirectToAction(nameof(Login));
        }

        #endregion
    }
}

nevladinaOrg.Web/Views/Shared/Partials/_AsideLeft.cshtml
@inject Localizer Localizer

@{
    var loggedUser = Context.GetLoggedUserData();

}
<!-- BEGIN: Left Aside -->
<button class="m-aside-left-close  m-aside-left-close--skin-light " id="m_aside_left_close_btn">
    <i class="la la-close"></i>
</button>
<div id="m_aside_left" class="m-grid__item m-aside-left  m-aside-left--skin-light ">
    <!-- BEGIN: Aside Menu -->
    <div id="m_ver_menu" class="m-aside-menu m-aside-menu--skin-light m-aside-menu--submenu-skin-dark m-scroller ps ps--active-y " m-menu-vertical="1" m-menu-scrollable="1" m-menu-dropdown-timeout="500" style="position: relative;">
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
            <li class="m-menu__item m-menu__item--active " aria-haspopup="true">
                <a href="@Url.Action("Index", "Home", new { area = string.Empty })" class="m-menu__link">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">@Localizer.Dashboard</span>
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__item  m-menu__item" aria-haspopup="true" is-visible="@(loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.Institution) || loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.System))">
                <a href="@Url.Action("Index", "Staff", new { area = nameof(nevladinaOrg.Web.Areas.Institutions) })" class="m-menu__link ">
                    <i class="m-menu__link-icon la la-users"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">@Localizer.InstitutionStaff</span>
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__item  m-menu__item" aria-haspopup="true" is-visible="@(loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.Institution) || loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.System))">
                <a href="@Url.Action("Index", "Members", new { area = nameof(nevladinaOrg.Web.Areas.Organizations) })" class="m-menu__link ">
                    <i class="m-menu__link-icon la la-users"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">@Localizer.Members</span>
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__item  m-menu__item" aria-haspopup="true" is-visible="@(loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.Institution) || loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.System))">
                <a href="@Url.Action("Index", "Events", new { area = nameof(nevladinaOrg.Web.Areas.Administration) })" class="m-menu__link ">
                    <i class="m-menu__link-icon la la-building-o"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">@Localizer.Events</span>
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__section ">
                <h4 class="m-menu__section-text">@Localizer.Settings</h4>
                <i class="m-menu__section-icon flaticon-more-v2"></i>
            </li>
            <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" m-menu-submenu-toggle="hover" is-visible="@loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.System)">
                <a href="javascript:;" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-layers"></i>
                    <span class="m-menu__link-text">@Localizer.System</span>
                    <i class="m-menu__ver-arrow la la-angle-right"></i>
                </a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true">
                            <span class="m-menu__link">
                                <span class="m-menu__link-text">@Localizer.System</span>
                            </span>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true">
                            <a href="@Url.Action("General", "SystemSettings", new { area = nameof(nevladinaOrg.Web.Areas.Administration) })" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">@Localizer.General</span>
                            </a>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true">
                            <a href="@Url.Action("Regional", "SystemSettings", new { area = nameof(nevladinaOrg.Web.Areas.Administration) })" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">@Localizer.Regional</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" m-menu-submenu-toggle="hover" is-visible="@(loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.Institution) || loggedUser.Roles.Select(x=>x.RoleLevel).Contains((int)Enumerations.RoleLevels.System))">
                <a href="javascript:;" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-layers"></i>
                    <span class="m-menu__link-text">@Localizer.Institutions</span>
                    <i class="m-menu__ver-arrow la la-angle-right"></i>
                </a>
                <div class="m-menu__submenu ">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true">
                            <span class="m-menu__link">
                                <span class="m-menu__link-text">@Localizer.InstitutionalSettings</span>
                            </span>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true">
                            <a href="@Url.Action("General", "InstitutionalSettings", new { area = nameof(nevladinaOrg.Web.Areas.Administration) })" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">@Localizer.General</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="m-menu__item  m-menu__item" aria-haspopup="true">
                <a href="@Url.Action("Index", "Announcements", new { area = nameof(nevladinaOrg.Web.Areas.Administration) })" class="m-menu__link ">
                    <i class="m-menu__link-icon la la-info"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">@Localizer.Announcements</span>
                        </span>
                    </span>
                </a>
            </li>


        </ul>
    </div>
    <!-- END: Aside Menu -->
</div>
<!-- END: Left Aside -->

nevladinaOrg.Web/Views/Shared/Partials/_HeaderBase.cshtml
<!-- BEGIN: Header -->
<header id="m_header" class="m-grid__item m-header " m-minimize-offset="200" m-minimize-mobile-offset="200">
    <div class="m-container m-container--fluid m-container--full-height">
        <div class="m-stack m-stack--ver m-stack--desktop">
            @{ await Html.RenderPartialAsync("Partials/_HeaderBrand"); }
            <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
                @{ await Html.RenderPartialAsync("Partials/_HeaderHorMenu"); }
                @{ await Html.RenderPartialAsync("Partials/_HeaderTopbar"); }
            </div>
        </div>
    </div>
</header>
<!-- END: Header -->

nevladinaOrg.Web/Views/Shared/Partials/_ModalLayout.cshtml
<div id="modalReplacement">
    @RenderSection("scripts", required: false)

    @RenderBody()
</div>

nevladinaOrg.Web/Views/Shared/Partials/_ScrollTop.cshtml
<!-- begin::Scroll Top -->
<div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
</div>
<!-- end::Scroll Top -->

nevladinaOrg.Web/Views/Shared/Partials/_TopbarUserProfile.cshtml
@{
    var loggedUser = Context.GetLoggedUserData();
}

<li class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img  m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light" m-dropdown-toggle="click">
    <a href="#" class="m-nav__link m-dropdown__toggle">
        <span class="m-topbar__userpic">
            <img src="~/app/media/img/users/male-profile-placeholder.png" class="m--img-rounded m--marginless" alt="" />
        </span>
        <span class="m-topbar__username m--hide">@loggedUser.PersonUser.FirstName @loggedUser.PersonUser.LastName</span>
    </a>
    <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
        <div class="m-dropdown__inner">
            <div class="m-dropdown__header m--align-center" style="background: url(/app/media/img/misc/user_profile_bg.jpg); background-size: cover;">
                <div class="m-card-user m-card-user--skin-dark">
                    <div class="m-card-user__pic">
                        <img src="~/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless" alt="" />
                        <!--<span class="m-type m-type--lg m--bg-danger"><span class="m--font-light">S<span><span>						-->
                    </div>
                    <div class="m-card-user__details">
                        <span class="m-card-user__name m--font-weight-500">@loggedUser.PersonUser.FirstName @loggedUser.PersonUser.LastName</span>
                        <a href="" class="m-card-user__email m--font-weight-300 m-link">@loggedUser.PersonUser.Email</a>
                    </div>
                </div>
            </div>
            <div class="m-dropdown__body">
                <div class="m-dropdown__content">
                    <ul class="m-nav m-nav--skin-light">
                        <li class="m-nav__section m--hide">
                            <span class="m-nav__section-text">Section</span>
                        </li>
                        <li class="m-nav__item">
                            <a href="?page=header/profile" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-profile-1"></i>
                                <span class="m-nav__link-title">
                                    <span class="m-nav__link-wrap">
                                        <span class="m-nav__link-text">My Profile</span>
                                        <span class="m-nav__link-badge">
                                        </span>
                                    </span>
                                </span>
                            </a>
                        </li>
                        <li class="m-nav__item">
                            <a href="?page=header/profile" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-share"></i>
                                <span class="m-nav__link-text">Activity</span>
                            </a>
                        </li>
                        <li class="m-nav__item">
                            <a href="?page=header/profile" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-chat-1"></i>
                                <span class="m-nav__link-text">Messages</span>
                            </a>
                        </li>
                        <li class="m-nav__separator m-nav__separator--fit"></li>
                        <li class="m-nav__item">
                            <a href="?page=header/profile" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-lifebuoy"></i>
                                <span class="m-nav__link-text">Support</span>
                            </a>
                        </li>
                        <li class="m-nav__separator m-nav__separator--fit"></li>
                        <li class="m-nav__item">
                            <a href="@Url.Action("Logout", "Access", new { area = string.Empty })" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>